### ISSUE TITLE
执行错误

### ISSUE THREAD

**Issue by 0xqq** [Bjq94/NER_homework#1]
Traceback (most recent call last):
  File "BERT-BiLSTM-CRF-NER/run.py", line 46, in <module>
    train_ner()
  File "BERT-BiLSTM-CRF-NER/run.py", line 39, in train_ner
    train(args=args)
  File "/bdp/nlp/BDCI_NER/src/BERT-BiLSTM-CRF-NER/bert_base/train/bert_lstm_ner.py", line 652, in train
    with codecs.open(os.path.join(args.output_dir, 'label2id.pkl'), 'rb') as rf:
  File "/home/lee/anaconda3/envs/kg_nlp/lib/python3.7/codecs.py", line 904, in open
    file = builtins.open(filename, mode, buffering)
FileNotFoundError: [Errno 2] No such file or directory: '../model/label2id.pkl'
Traceback (most recent call last):
  File "post_process.py", line 58, in <module>
    encoding="utf-8") as r_repo:
FileNotFoundError: [Errno 2] No such file or directory: '../model/label_test_final_repro.txt'

**Comment by Bjq94** [comment]
Thanks， this bug has been fixed.

**Comment by Bjq94** [comment]
If you have other issues, please show me in time. :D
